
unset alfred_workflow_bundleid
unset alfred_workflow_version
unset alfred_workflow_name
unset alfred_workflow_data
unset alfred_workflow_cache

unset INTERVAL_FIND
unset INTERVAL_MDFIND
unset INTERVAL_LOCATE

