[run]
deadline = "5m"

[linters]
disable-all = true
enable = [
  "deadcode",
  "goconst",
  "gofmt",
  "gosimple",
  "goimports",
  "ineffassign",
  "scopelint",
  "staticcheck",
  "stylecheck",
  "unconvert",
  "unused",
]

[linter-settings]
  [linter-settings.errcheck]
  check-blank = true
  check-type-assertions = true

[issues]
  max-same-issues = 50
  max-issues-per-linter = 50
